---
format:
  html:
    minimal: true
---

```{r}
#| label: GetDataCRAN
#| message: false
#| warning: false
#| include: false

library(cranlogs)
library(tools)

# Get statistics total cran downloads
cran_downloads_last_day <- cranlogs::cran_downloads(when = "last-day")
cran_downloads_last_day_count <- cran_downloads_last_day$count
cran_downloads_last_week <- cranlogs::cran_downloads(when = "last-week")
cran_downloads_last_week_count <- sum(cran_downloads_last_week$count, na.rm = TRUE)
cran_downloads_last_month <- cranlogs::cran_downloads(when = "last-month")
cran_downloads_last_month_count <- sum(cran_downloads_last_month$count, na.rm = TRUE)

# Monthly cran downloads of top 100 most downloaded R package
#cran_downloads_last_day_top100 <- cranlogs::cran_top_downloads(count = 100, when = "last-day")
#cran_downloads_last_week_top100 <- cranlogs::cran_top_downloads(count = 100, when = "last-week")
#cran_downloads_last_month_top100 <- cranlogs::cran_top_downloads(count = 100, when = "last-month")

# Current package in CRAN information
#cran_package_data_all <- tools::CRAN_package_db()
```

```{r}
#| label: StatCard
#| message: false
#| warning: false
#| include: false

library(shinyMaterialUI)
library(scales) # for number() function

# StatCard() adapted from MUI example:
# https://github.com/mui/material-ui/blob/v7.0.2/docs/data/material/getting-started/templates/dashboard/components/StatCard.js
StatCard <- function(title, value) {
  Card(
    variant = "outlined",
    sx = list(height = '100%', flexGrow = 1),
    CardContent(
      Typography(
        title,
        component = "h2",
        variant = "subtitle2",
        gutterBottom = TRUE
      ),
      Stack(
        direction = "column",
        sx = list(justifyContent = 'space-between', flexGrow = '1', gap = 1),
        Stack(
          sx = list(justifyContent = 'space-between'),
          Stack(
            direction = "row",
            sx = list(justifyContent = 'space-between', alignItems = 'center'),
            Typography(
              variant = "h4",
              component = "p",
              scales::number(
                x = value, 
                accuracy = 0.1, 
                scale_cut = scales::cut_long_scale()
              )
            ),
            Chip(
              size = "small",
              color = "success",
              label = "0.5%"
            )
          )
        ),
        Box(
          sx = list(width = '100%', height = 50),
          Typography("Test")
        )
      )
    )
  )
}
```


```{r}
#| echo: false
#| message: false
#| warning: false

library(shinyMaterialUI)
library(reactRouter)

reactRouter::HashRouter(
  ThemeProvider(
    theme = list(
      palette = list(
        mode = "light", # "dark" for dark theme
        # overwrite default theme
        primary = list(
          main = "#5e72e4"
        ),
        background = list(
          default = "#fafafa"
        )
      )
  ),
  CssBaseline(
  Box(
    sx = list(flexGrow = 1),
    AppBar(
      position = "fixed",
      Toolbar(
        Typography(
          "CRAN explorer",
          variant = "h6",
          component = "div",
          sx = list(flexGrow = 1)
        )
      )
    ),
    Box(
      component = "main",
      sx = list(flexGrow = 1),
      Toolbar(),
      Routes(
        Route(
          path = "/",
          element = Box(
            sx = list(width = '100%'),
            Typography(
              component = "h2",
              variant = "h6",
              m = 2,
              sx = list(fontWeight = 600),
              "Total downloads"
            ),
            Grid(
              container = TRUE,
              m = 2,
              spacing = 2,
              columns = 12,
              Grid(
                size = list(xs = 12, sm = 6, lg = 3),
                StatCard(
                  title = "Yesterday", 
                  value = cran_downloads_last_day_count
                )
              ),
              Grid(
                size = list(xs = 12, sm = 6, lg = 3),
                StatCard(
                  title = "Last week", 
                  value = cran_downloads_last_week_count
                )
              ),
              Grid(
                size = list(xs = 12, sm = 6, lg = 3),
                StatCard(
                  title = "Last month", 
                  value = cran_downloads_last_month_count
                )
              ),
              Grid(
                size = list(xs = 12, sm = 6, lg = 3),
                Card(
                  variant = "outlined",
                  sx = list(height = '100%'),
                  CardContent(
                    #shiny::icon("circle-info"),
                    Typography(
                      component = "h2",
                      variant = "subtitle2",
                      gutterBottom = TRUE,
                      sx = list(fontWeight = '600'),
                      shiny::icon("circle-info"), " Learn more about shinyMaterialUI"
                    ),
                    Button(
                      variant = "contained",
                      size = "small",
                      color = "primary",
                      endIcon = shiny::icon("chevron-right"),
                      "Read the docs"
                    )
                  )
                )
              )
            )
          )
        ),
        Route(
          path = "/analytics",
          element = Box(
            sx = list(margin = 2),
            Typography("Analytics", variant = "h6", component = "h2"),
            Typography("Content analytics")
          )
        )
      )
    )
  )
)))
```
