# Examples for the component help pages. R/components.R and R/documentation.R
# are generated by dev/generate-components-docs-tests.R, so the examples live
# here: each block is merged into the topic named by @rdname. The articles of
# the pkgdown website have many more examples.

#' @examples
#' Accordion(
#'   AccordionSummary("Accordion 1"),
#'   AccordionDetails("Lorem ipsum dolor sit amet.")
#' )
#' @rdname Accordion
#' @name Accordion
NULL

#' @examples
#' Alert(severity = "warning", AlertTitle("Warning"), "This is a warning Alert.")
#' @rdname Alert
#' @name Alert
NULL

#' @examples
#' AppBar(
#'   position = "static",
#'   Toolbar(
#'     Typography(variant = "h6", sx = list(flexGrow = 1), "News"),
#'     Button(color = "inherit", "Login")
#'   )
#' )
#' @rdname AppBar
#' @name AppBar
NULL

#' @examples
#' Stack(
#'   direction = "row", spacing = 2,
#'   Avatar("H"), Avatar(sx = list(bgcolor = "secondary.main"), "N")
#' )
#' @rdname Avatar
#' @name Avatar
NULL

#' @examples
#' Badge(badgeContent = 4, color = "primary", Button("Messages"))
#' @rdname Badge
#' @name Badge
NULL

#' @examples
#' Box(component = "section", sx = list(p = 2, border = "1px dashed grey"), "A section")
#' @rdname Box
#' @name Box
NULL

#' @examples
#' Breadcrumbs(
#'   Link(underline = "hover", color = "inherit", href = "#", "Home"),
#'   Typography(sx = list(color = "text.primary"), "Current page")
#' )
#' @rdname Breadcrumbs
#' @name Breadcrumbs
NULL

#' @examples
#' ButtonGroup(variant = "contained", Button("One"), Button("Two"), Button("Three"))
#' @rdname ButtonGroup
#' @name ButtonGroup
NULL

#' @examples
#' Card(
#'   sx = list(maxWidth = 345),
#'   CardContent(
#'     Typography(variant = "h5", "Lizard"),
#'     Typography(variant = "body2", sx = list(color = "text.secondary"), "Lizards are reptiles.")
#'   ),
#'   CardActions(Button(size = "small", "Learn More"))
#' )
#' @rdname Card
#' @name Card
NULL

#' @examples
#' FormGroup(
#'   FormControlLabel(control = Checkbox(defaultChecked = TRUE), label = "Label"),
#'   FormControlLabel(control = Checkbox(), label = "Disabled", disabled = TRUE)
#' )
#' @examplesIf interactive()
#' library(shiny)
#' ui <- muiMaterialPage(Checkbox.shinyInput("agree", value = FALSE), verbatimTextOutput("out"))
#' server <- function(input, output, session) output$out <- renderPrint(input$agree)
#' shinyApp(ui, server)
#' @rdname Checkbox
#' @name Checkbox
NULL

#' @examples
#' Stack(
#'   direction = "row", spacing = 1,
#'   Chip(label = "Filled"), Chip(label = "Outlined", variant = "outlined")
#' )
#' @rdname Chip
#' @name Chip
NULL

#' @examples
#' Stack(
#'   direction = "row", spacing = 2,
#'   CircularProgress(), CircularProgress(variant = "determinate", value = 75)
#' )
#' @rdname CircularProgress
#' @name CircularProgress
NULL

#' @examples
#' Container(maxWidth = "sm", Box(sx = list(bgcolor = "#cfe8fc", height = 200)))
#' @rdname Container
#' @name Container
NULL

#' @examples
#' # Opened by the server with updateDialog.shinyInput(); see also Dialog.triggerId()
#' Dialog(open = TRUE, DialogTitle("Title"), DialogContent(DialogContentText("Content")))
#' @examplesIf interactive()
#' library(shiny)
#' ui <- muiMaterialPage(
#'   Button.shinyInput("open", "Open dialog"),
#'   Dialog.shinyInput(
#'     inputId = "dialog",
#'     open = FALSE,
#'     onClose = triggerEvent("close"),
#'     DialogTitle("Hello"),
#'     DialogActions(Button.shinyInput("ok", "OK"))
#'   )
#' )
#' server <- function(input, output, session) {
#'   observeEvent(input$open, updateDialog.shinyInput(inputId = "dialog", open = TRUE))
#'   observeEvent(input$close, updateDialog.shinyInput(inputId = "dialog", open = FALSE))
#'   observeEvent(input$ok, updateDialog.shinyInput(inputId = "dialog", open = FALSE))
#' }
#' shinyApp(ui, server)
#' @rdname Dialog
#' @name Dialog
NULL

#' @examples
#' List(
#'   ListItem(ListItemText(primary = "Inbox")),
#'   Divider(),
#'   ListItem(ListItemText(primary = "Drafts"))
#' )
#' @rdname Divider
#' @name Divider
NULL

#' @examples
#' # A permanent drawer; for a drawer opened by a button, see Drawer.triggerId()
#' Drawer(variant = "permanent", List(ListItemButton(ListItemText(primary = "Inbox"))))
#' @rdname Drawer
#' @name Drawer
NULL

#' @examples
#' Fab(color = "primary", `aria-label` = "add", "+")
#' @rdname Fab
#' @name Fab
NULL

#' @examples
#' Grid(
#'   container = TRUE,
#'   spacing = 2,
#'   Grid(size = list(xs = 12, md = 8), Paper(sx = list(p = 1), "size=8")),
#'   Grid(size = list(xs = 12, md = 4), Paper(sx = list(p = 1), "size=4"))
#' )
#' @rdname Grid
#' @name Grid
NULL

#' @examples
#' # Needs the Material Icons font: muiMaterialPage(useMaterialIconsFilled = TRUE)
#' muiMaterialPage(useMaterialIconsFilled = TRUE, Icon("home"), Icon("star", color = "primary"))
#' @rdname Icon
#' @name Icon
NULL

#' @examples
#' IconButton(`aria-label` = "delete", shiny::icon("trash"))
#' @rdname IconButton
#' @name IconButton
NULL

#' @examples
#' Box(sx = list(width = "100%"), LinearProgress(variant = "determinate", value = 40))
#' @rdname LinearProgress
#' @name LinearProgress
NULL

#' @examples
#' Link(href = "https://mui.com", underline = "hover", "MUI")
#' @rdname Link
#' @name Link
NULL

#' @examples
#' List(
#'   ListItem(disablePadding = TRUE, ListItemButton(ListItemText(primary = "Inbox"))),
#'   ListItem(disablePadding = TRUE, ListItemButton(ListItemText(primary = "Drafts")))
#' )
#' @rdname List
#' @name List
NULL

#' @examples
#' # For a menu opened by a button, see Menu.triggerId()
#' Paper(MenuList(MenuItem("Profile"), MenuItem("My account"), MenuItem("Logout")))
#' @rdname MenuList
#' @name MenuList
NULL

#' @examples
#' Stack(
#'   spacing = 2,
#'   Pagination(count = 10),
#'   Pagination(count = 10, color = "primary", variant = "outlined")
#' )
#' @examplesIf interactive()
#' library(shiny)
#' ui <- muiMaterialPage(Pagination.shinyInput("page", count = 10), verbatimTextOutput("out"))
#' server <- function(input, output, session) output$out <- renderPrint(input$page)
#' shinyApp(ui, server)
#' @rdname Pagination
#' @name Pagination
NULL

#' @examples
#' Stack(
#'   direction = "row", spacing = 2,
#'   Paper(elevation = 0, "0"), Paper("1"), Paper(elevation = 3, "3")
#' )
#' @rdname Paper
#' @name Paper
NULL

#' @examples
#' RadioGroup(
#'   defaultValue = "female",
#'   name = "gender",
#'   FormControlLabel(value = "female", control = Radio(), label = "Female"),
#'   FormControlLabel(value = "male", control = Radio(), label = "Male")
#' )
#' @examplesIf interactive()
#' library(shiny)
#' ui <- muiMaterialPage(
#'   RadioGroup.shinyInput(
#'     inputId = "gender",
#'     value = "female",
#'     FormControlLabel(value = "female", control = Radio(), label = "Female"),
#'     FormControlLabel(value = "male", control = Radio(), label = "Male")
#'   ),
#'   verbatimTextOutput("out")
#' )
#' server <- function(input, output, session) output$out <- renderPrint(input$gender)
#' shinyApp(ui, server)
#' @rdname RadioGroup
#' @name RadioGroup
NULL

#' @examples
#' Rating(defaultValue = 3)
#' @examplesIf interactive()
#' library(shiny)
#' ui <- muiMaterialPage(Rating.shinyInput("stars", value = 3), verbatimTextOutput("out"))
#' server <- function(input, output, session) output$out <- renderPrint(input$stars)
#' shinyApp(ui, server)
#' @rdname Rating
#' @name Rating
NULL

#' @examples
#' FormControl(
#'   sx = list(minWidth = 120),
#'   InputLabel(id = "age-label", "Age"),
#'   Select(
#'     labelId = "age-label", label = "Age", defaultValue = 10,
#'     MenuItem(value = 10, "Ten"), MenuItem(value = 20, "Twenty")
#'   )
#' )
#' @examplesIf interactive()
#' library(shiny)
#' ui <- muiMaterialPage(
#'   FormControl(
#'     sx = list(m = 2, minWidth = 120),
#'     InputLabel(id = "age-label", "Age"),
#'     Select.shinyInput("age", labelId = "age-label", label = "Age", value = 10,
#'       MenuItem(value = 10, "Ten"), MenuItem(value = 20, "Twenty"))
#'   ),
#'   verbatimTextOutput("out")
#' )
#' server <- function(input, output, session) output$out <- renderPrint(input$age)
#' shinyApp(ui, server)
#' @rdname Select
#' @name Select
NULL

#' @examples
#' Stack(
#'   spacing = 1,
#'   Skeleton(variant = "text"),
#'   Skeleton(variant = "rectangular", width = 210, height = 60)
#' )
#' @rdname Skeleton
#' @name Skeleton
NULL

#' @examples
#' # Opened by the server with updateSnackbar.shinyInput()
#' Snackbar(open = TRUE, message = "Note archived")
#' @examplesIf interactive()
#' library(shiny)
#' ui <- muiMaterialPage(
#'   Button.shinyInput("save", "Save"),
#'   Snackbar.shinyInput("snackbar", open = FALSE, autoHideDuration = 3000,
#'     message = "Saved!", onClose = triggerEvent("snackbar_close"))
#' )
#' server <- function(input, output, session) {
#'   observeEvent(input$save, updateSnackbar.shinyInput(inputId = "snackbar", open = TRUE))
#'   observeEvent(input$snackbar_close, updateSnackbar.shinyInput(inputId = "snackbar", open = FALSE))
#' }
#' shinyApp(ui, server)
#' @rdname Snackbar
#' @name Snackbar
NULL

#' @examples
#' Stack(direction = "row", spacing = 2, divider = Divider(orientation = "vertical", flexItem = TRUE),
#'   Paper("Item 1"), Paper("Item 2"), Paper("Item 3"))
#' @rdname Stack
#' @name Stack
NULL

#' @examples
#' Stepper(
#'   activeStep = 1,
#'   Step(StepLabel("Select settings")),
#'   Step(StepLabel("Create a group")),
#'   Step(StepLabel("Create an ad"))
#' )
#' @rdname Stepper
#' @name Stepper
NULL

#' @examples
#' FormControlLabel(control = Switch(defaultChecked = TRUE), label = "Label")
#' @examplesIf interactive()
#' library(shiny)
#' ui <- muiMaterialPage(Switch.shinyInput("dark", value = FALSE), verbatimTextOutput("out"))
#' server <- function(input, output, session) output$out <- renderPrint(input$dark)
#' shinyApp(ui, server)
#' @rdname Switch
#' @name Switch
NULL

#' @examples
#' data <- head(mtcars[, 1:3])
#' TableContainer(
#'   Table(
#'     size = "small",
#'     TableHead(TableRow(
#'       TableCell("Car"),
#'       lapply(names(data), function(col) TableCell(align = "right", col))
#'     )),
#'     TableBody(lapply(seq_len(nrow(data)), function(i) {
#'       TableRow(
#'         TableCell(component = "th", scope = "row", rownames(data)[i]),
#'         lapply(names(data), function(col) TableCell(align = "right", data[[col]][i]))
#'       )
#'     }))
#'   )
#' )
#' @rdname Table
#' @name Table
NULL

#' @examples
#' # Tabs report the selected value to the server; for client-side tabs,
#' # see TabContext.static()
#' Tabs(value = "one", Tab(label = "Item One", value = "one"), Tab(label = "Item Two", value = "two"))
#' @examplesIf interactive()
#' library(shiny)
#' ui <- muiMaterialPage(
#'   Tabs.shinyInput(
#'     "tab", value = "one",
#'     Tab(label = "One", value = "one"), Tab(label = "Two", value = "two")
#'   ),
#'   verbatimTextOutput("out")
#' )
#' server <- function(input, output, session) output$out <- renderPrint(input$tab)
#' shinyApp(ui, server)
#' @rdname Tabs
#' @name Tabs
NULL

#' @examples
#' Timeline(
#'   TimelineItem(TimelineSeparator(TimelineDot(), TimelineConnector()), TimelineContent("Eat")),
#'   TimelineItem(TimelineSeparator(TimelineDot()), TimelineContent("Sleep"))
#' )
#' @rdname Timeline
#' @name Timeline
NULL

#' @examples
#' ToggleButtonGroup(
#'   value = "left",
#'   exclusive = TRUE,
#'   ToggleButton(value = "left", "Left"),
#'   ToggleButton(value = "center", "Center")
#' )
#' @examplesIf interactive()
#' library(shiny)
#' ui <- muiMaterialPage(
#'   ToggleButtonGroup.shinyInput("align", value = "left", exclusive = TRUE,
#'     ToggleButton(value = "left", "Left"), ToggleButton(value = "center", "Center")),
#'   verbatimTextOutput("out")
#' )
#' server <- function(input, output, session) output$out <- renderPrint(input$align)
#' shinyApp(ui, server)
#' @rdname ToggleButtonGroup
#' @name ToggleButtonGroup
NULL

#' @examples
#' Tooltip(title = "Delete", Button("Hover me"))
#' @rdname Tooltip
#' @name Tooltip
NULL

#' @examples
#' Box(Typography(variant = "h1", "h1. Heading"), Typography(variant = "body1", "body1. Text"))
#' @rdname Typography
#' @name Typography
NULL

#' @examples
#' # Client-side tabs: no Shiny server needed
#' TabContext.static(
#'   defaultValue = "one",
#'   Box(
#'     sx = list(borderBottom = 1, borderColor = "divider"),
#'     TabList.static(Tab(label = "Item One", value = "one"), Tab(label = "Item Two", value = "two"))
#'   ),
#'   TabPanel(value = "one", "Content 1"),
#'   TabPanel(value = "two", "Content 2")
#' )
#' @rdname TabContext
#' @name TabContext
NULL
